### PR TITLE
Loading animations on Zerif

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Will add loading animations on Zerif. RokoPhoto doesn't have loading animations in its default form either so didn't add that. Hope it's the right way.

@rodica-andronache

### CODE REVIEW

**Comment by ineagu** [comment]
@rodica-andronache  ?

**Comment by rodica-andronache** [comment]
@HardeepAsrani sorry for not answering before :)
what you did it's working, the only concern I have about this is what's happening for the users that have the    form on other internal pages ,not the frontpage. because in that case, it looks weird with that effect.
What do you think? there are many users with zerif ,and the contact form

**Comment by HardeepAsrani** [comment]
@rodica-andronache Are we even loading revealscroll on inner pages?

**Comment by rodica-andronache** [comment]
@HardeepAsrani I tested with zerif lite yesterday, and it seems that we are loading it on inner pages too

**Comment by HardeepAsrani** [comment]
@rodica-andronache We can check if the front-page.php file is being used, what say? :)

**Comment by rodica-andronache** [comment]
it's more complicated now for zerif, as the frontpage condition is different for old/new users, and there are more cases

**Pull request closed without merging**
